# Generated by Django 5.2.8 on 2025-12-15 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='table_no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
