# Generated by Django 5.2.8 on 2025-12-15 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_remove_order_table_no_orderitem_table_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='table_no',
        ),
        migrations.AddField(
            model_name='order',
            name='table_no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
