# Generated by Django 5.2.8 on 2025-12-29 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_remove_orderitem_table_no_order_table_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='quantity',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=3),
        ),
    ]
