# Generated by Django 5.2.8 on 2025-12-29 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_menuitem_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='quantity',
            new_name='menu_quantity',
        ),
    ]
