# Generated by Django 5.2.8 on 2025-12-29 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0006_rename_quantity_menuitem_menu_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='menu_quantity',
            field=models.DecimalField(decimal_places=3, default=1.0, max_digits=6),
        ),
    ]
